### PR TITLE
manage dependencies with pipenv

### PR DESCRIPTION
**Pull request by wolfg1969**

### CODE REVIEW

**Comment by yihong0618** [comment]
I think requirements for this repo is enough？
maybe we can just lock the version？

**Comment by frostming** [comment]
I am just -1 for pipenv 😅

**Comment by yihong0618** [comment]
@wolfg1969 can you just fix the version then we merge this?

**Comment by frostming** [comment]
Sorry, we don't plan to use a dependency manager yet. This project is mainly targeted at non-programmers, introducing Pipenv will bring an extra dependency.

I am going to close it for now.

**Pull request closed without merging**
